postgres {
  url = "jdbc:postgresql://postgres_container:5432/retail"
  user = "student"
  password = "student_pass"
  schema = "data"

  tables = [
    "banks",
    "cards",
    "mcc",
    "organizations",
    "peoples"
  ]
}

hdfs {
  rawPath = "hdfs://namenode:9000/raw"
}

kafka {

  bootstrapServers = "kafka1:19092"

  topics = [
    "amur_topic",
    "neva_topic",
    "ob_topic",
    "volga_topic",
    "yenisei_topic"
  ]

  checkpoint = "hdfs://namenode:9000/checkpoints/kafka_raw"

  output = "hdfs://namenode:9000/raw/kafka_transactions"

  trigger = "30 seconds"

  startingOffsets = "latest"
}